name: PR on qa

on:
  pull_request:
    branches:
      - qa
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Unit test
        run: npm run test
    